import { Play, Target, Wall } from "@phosphor-icons/react";
import { ElementProps } from "./components/elements/element";
import { CellTypes } from "./components/maze/cell";
import solverBFS from "./solvers/BFS";
import solverDFS from "./solvers/DFS";

export interface Coordinates {
  row: number;
  col: number;
}

export interface CandidatesProps {
  action: "up" | "down" | "left" | "right";
  coordinates: Coordinates;
}

export interface AlgorithmsProps {
  name: string;
  solver: (
    cells: CellProps[][],
    setCellValue: (row: number, col: number, value: CellTypes) => void
  ) => void;
}

export const selectElements: ElementProps[] = [
  {
    title: "Start Node",
    cellValue: "A",
    icon: Play,
  },
  {
    title: "Target Node",
    cellValue: "B",
    icon: Target,
  },
  {
    title: "Wall Node",
    cellValue: "#",
    icon: Wall,
  },
];

export const algorithms: AlgorithmsProps[] = [
  {
    name: "Breath-First Search",
    solver: solverBFS,
  },
  {
    name: "Depth-First Search",
    solver: solverDFS,
  },
  {
    name: "A* Search",
    solver: solverBFS,
  },
];

export function generateCandidates(state: Coordinates): CandidatesProps[] {
  const { row, col } = state;

  const candidates: CandidatesProps[] = [
    {
      action: "up",
      coordinates: {
        row: row - 1,
        col,
      },
    },
    {
      action: "down",
      coordinates: {
        row: row + 1,
        col,
      },
    },
    {
      action: "left",
      coordinates: {
        row,
        col: col - 1,
      },
    },
    {
      action: "right",
      coordinates: {
        row,
        col: col + 1,
      },
    },
  ];

  return candidates.filter(
    (candidate) =>
      candidate.coordinates.row >= 0 &&
      candidate.coordinates.col >= 0 &&
      candidate.coordinates.row <= rows - 1 &&
      candidate.coordinates.col <= columns - 1
  );
}

//  Maze utils
const rows = 15;
const columns = 30;

export interface CellProps {
  value: CellTypes;
}

const initialCell: CellProps = {
  value: null,
};

export const initialGrid: CellProps[][] = Array.from({ length: rows }, () =>
  new Array(columns).fill(initialCell)
);

export const customMaze: CellProps[][] = [
  [
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
  ],
  [
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
  ],
  [
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
  ],
  [
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
  ],
  [
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
  ],
  [
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
  ],
  [
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
  ],
  [
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
  ],
  [
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
  ],
  [
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
  ],
  [
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
  ],
  [
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
  ],
  [
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: "#" },
  ],
  [
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
  ],
  [
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: null },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
    { value: "#" },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: null },
    { value: "#" },
  ],
];
